"0|Myles Munroe",
"1|Kenneth E Hagin",
"2|Bishop David Oyedepo",
"3|Admin",
"4|Youths",
"5|Jesse Duplantis",
"6|Andrew Wommack",
"7|Pastor E.A. Adeboye",
"8|Pure Flix Entertainment",
"9|Christiano Film Group",
"10|TD Jakes",
"11|Akatio Films",
"12|John Maxwell",
"13|John Bunyan",
"14|Kenneth Copeland",
"15|Mel Gibson",
"16|Charles Capps",
"17|Dave Stotts"